### ISSUE TITLE
optimize performance

### ISSUE THREAD

**Issue by qq1053831109** [inwc3/JMPQ3#44]
![QQ截图20220726133847](https://user-images.githubusercontent.com/17372170/181144262-0e49cdcd-603d-47ff-97fe-d5bfe7f5f80e.png)

Use multithreading to perform compression algorithms！

Now the maps are all 500MB.

**Comment by Frotty** [comment]
If you want multi-threaded anything consider making a unit tested pull request, it's not something I am gonna look into.

Are you using the latest version (1.9.6)? If you aren't specifying `recompress` it will choose the fastest compression configuration which only takes ~10 seconds for 100MB for me.

In any case your problem is mostly related to your usage of jmpq. If you have a 500mb input map and only change a couple files, it will be almost instant, because only the new files need to be compressed.
But you are building a fresh mpq, adding many hundreds of source files which all need to be compressed each time you do this. If you really want fast write performance in your editor you need to cache the output mpq file on your end and then only update changes to the cached file, instead of building the entire mpq every time. This is the real solution to your problem.
